// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQAGAGzBsFRYhty1J06XXJAOzjin_jlOk',
    appId: '1:789637645577:web:087f1fdd7dd7eb70d57fd8',
    messagingSenderId: '789637645577',
    projectId: 'anisync-b79b3',
    authDomain: 'anisync-b79b3.firebaseapp.com',
    storageBucket: 'anisync-b79b3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL0ikkO9LAUlmjrXsXKndUv7szfxM1VgI',
    appId: '1:789637645577:android:858ff92191eeeb47d57fd8',
    messagingSenderId: '789637645577',
    projectId: 'anisync-b79b3',
    storageBucket: 'anisync-b79b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAly9fdZ-_lnQam7htL_cmqo0yvVrdPuZk',
    appId: '1:789637645577:ios:7c351322f6297404d57fd8',
    messagingSenderId: '789637645577',
    projectId: 'anisync-b79b3',
    storageBucket: 'anisync-b79b3.firebasestorage.app',
    iosBundleId: 'com.example.anisyncFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAly9fdZ-_lnQam7htL_cmqo0yvVrdPuZk',
    appId: '1:789637645577:ios:7c351322f6297404d57fd8',
    messagingSenderId: '789637645577',
    projectId: 'anisync-b79b3',
    storageBucket: 'anisync-b79b3.firebasestorage.app',
    iosBundleId: 'com.example.anisyncFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQAGAGzBsFRYhty1J06XXJAOzjin_jlOk',
    appId: '1:789637645577:web:85fba8aa58eb1842d57fd8',
    messagingSenderId: '789637645577',
    projectId: 'anisync-b79b3',
    authDomain: 'anisync-b79b3.firebaseapp.com',
    storageBucket: 'anisync-b79b3.firebasestorage.app',
  );
}
